/*
 Problem 2
 -----------
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 -----------
 */

import Foundation

var fibonacciNumber = [1,2]
var nextFibonacci = fibonacciNumber[0] + fibonacciNumber[1]
var sum = 0
let ceiling = 4000000

while nextFibonacci < ceiling {
    nextFibonacci = fibonacciNumber[0] + fibonacciNumber[1]
    
    if nextFibonacci % 2 == 0 {
        sum += nextFibonacci
    }
    
    fibonacciNumber[0] = fibonacciNumber[1]
    fibonacciNumber[1] = nextFibonacci
}

print("The sum is: \(sum)")
